/** @vitest-environment node */
import {it,expect,vi,beforeEach,afterEach} from "vitest";
import {GET,POST} from "./route";
const id="10000000-0000-4000-8000-000000000001";
function req(body?:unknown,origin="http://localhost:3215"){return new Request("http://localhost:3215/api/management/operations?view=report",{method:body===undefined?"GET":"POST",headers:{host:"localhost:3215",origin,"Content-Type":"application/json",cookie:"ev-owner-access=synthetic"},body:body===undefined?undefined:JSON.stringify(body)});}
beforeEach(()=>{vi.stubEnv("NODE_ENV","development");vi.stubEnv("EV_MANAGEMENT_MODE","preview");vi.stubEnv("EV_CONVERSATION_STORAGE","staging");vi.stubEnv("VERCEL","");vi.stubEnv("SUPABASE_URL","https://example.supabase.co");vi.stubEnv("SUPABASE_PUBLISHABLE_KEY","sb_publishable_test");});afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals();});
it("denies production access and foreign-origin writes without database calls",async()=>{const f=vi.fn();vi.stubGlobal("fetch",f);expect((await POST(req({},"https://foreign.example"))).status).toBe(403);vi.stubEnv("NODE_ENV","production");expect((await GET(req())).status).toBe(404);expect((await POST(req({}))).status).toBe(404);expect(f).not.toHaveBeenCalled();});
it("rejects oversized bodies before authentication",async()=>{const f=vi.fn();vi.stubGlobal("fetch",f);expect((await POST(req({body:"x".repeat(128000)}))).status).toBe(400);expect(f).not.toHaveBeenCalled();});
it("returns a stale-revision conflict without replacing the user's draft",async()=>{const f=vi.fn();for(const v of [{id,is_anonymous:false},{owner:true,assured:true},{id,is_anonymous:false},{owner:true,assured:true}])f.mockResolvedValueOnce(Response.json(v));f.mockResolvedValueOnce(Response.json({code:"PT409"},{status:409}));vi.stubGlobal("fetch",f);const r=await POST(req({id,requestId:id,revision:0,title:"Title",body:"Unsaved fact",provenance:"Owner source",status:"draft"}));expect(r.status).toBe(409);expect(r.headers.get("cache-control")).toContain("no-store");expect(await r.json()).not.toHaveProperty("saved");});
