/** @vitest-environment node */
import {it,expect,vi} from "vitest";
import {ownerGapOperations,parseGapReview} from "./owner-gaps";
import {ownerAuth} from "./owner-session";
const id="10000000-0000-4000-8000-000000000001";
const review={messageId:id,requestId:id,revision:0,diagnosis:"unclassified" as const,status:"investigating" as const,note:"Synthetic note",draftId:null};
it("accepts only bounded human review fields",()=>{expect(parseGapReview({...review,owner_id:"forged",publish:true})).toEqual(review);for(const value of [{...review,status:"published"},{...review,revision:-1},{...review,note:"x".repeat(1001)},{...review,diagnosis:"guessed"},{...review,draftId:"bad"},{...review,status:"drafted"}])expect(()=>parseGapReview(value)).toThrow();});
it("keeps one request identity through save retries and verifies returned revision",async()=>{const call=vi.fn().mockResolvedValue({messageId:id,revision:1}),ops=ownerGapOperations(call);expect(await ops.reviewGap("token",review)).toEqual({messageId:id,revision:1});await ops.reviewGap("token",review);expect(call.mock.calls[0]).toEqual(call.mock.calls[1]);expect(call.mock.calls[0][2]).toMatchObject({p_message_id:id,p_request_id:id,p_expected_revision:0,p_diagnosis:"unclassified"});call.mockResolvedValue({messageId:id,revision:3});await expect(ops.reviewGap("token",review)).rejects.toMatchObject({kind:"unavailable"});});
it("rejects oversized or malformed queues",async()=>{const call=vi.fn().mockResolvedValue(Array.from({length:101},()=>({}))),ops=ownerGapOperations(call);await expect(ops.gaps("token")).rejects.toMatchObject({kind:"unavailable"});call.mockResolvedValue([{message_id:"bad"}]);await expect(ops.gaps("token")).rejects.toMatchObject({kind:"unavailable"});});
it("requires current owner MFA before any gap RPC",async()=>{const f=vi.fn().mockImplementation((url:string)=>Promise.resolve(Response.json(url.endsWith('/user')?{id,is_anonymous:false}:{owner:true,assured:false})));const auth=ownerAuth({projectUrl:"https://example.supabase.co",publishableKey:"sb_publishable_test"},AbortSignal.timeout(5000),f);await expect(auth.gaps("token")).rejects.toMatchObject({kind:"unauthorized"});await expect(auth.reviewGap("token",review)).rejects.toMatchObject({kind:"unauthorized"});expect(f.mock.calls.some(c=>String(c[0]).includes("ev_owner_gaps")||String(c[0]).includes("ev_review_gap"))).toBe(false);});
