/** @vitest-environment node */
import { afterEach,beforeEach,it,expect,vi } from "vitest";
import { mkdtemp,writeFile,readFile,rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { initializeOwner,ownerSetup } from "./owner-bootstrap";
let dir:string,path:string;
const id="10000000-0000-4000-8000-000000000001",config={projectUrl:"https://test-project.supabase.co",publishableKey:"sb_publishable_test"};
const setup=()=>({version:1,userId:id,email:"owner@example.test",expiresAt:new Date(Date.now()+3600000).toISOString()});
beforeEach(async()=>{vi.stubEnv("NODE_ENV","development");vi.stubEnv("EV_MANAGEMENT_MODE","preview");vi.stubEnv("VERCEL","");vi.stubEnv("EV_MANAGEMENT_TEST_STORE","");dir=await mkdtemp(join(tmpdir(),"ev-owner-setup-"));path=join(dir,"setup.json");await writeFile(path,JSON.stringify(setup()));});
afterEach(async()=>{vi.unstubAllEnvs();await rm(dir,{recursive:true,force:true});});
it("never offers expired, malformed or browser-test setup",async()=>{await writeFile(path,JSON.stringify({...setup(),expiresAt:new Date(Date.now()-1).toISOString()}));expect(await ownerSetup(path)).toBeNull();await writeFile(path,"broken");expect(await ownerSetup(path)).toBeNull();vi.stubEnv("EV_MANAGEMENT_TEST_STORE","1");expect(await ownerSetup(path)).toBeNull();});
it("denies production, weak passwords and an untrusted API origin before any request",async()=>{const f=vi.fn();vi.stubEnv("NODE_ENV","production");await expect(initializeOwner(config,"sb_secret_test","a-long-synthetic-password",AbortSignal.timeout(5000),f,path)).rejects.toMatchObject({kind:"unavailable"});vi.stubEnv("NODE_ENV","development");await expect(initializeOwner(config,"sb_secret_test","short",AbortSignal.timeout(5000),f,path)).rejects.toMatchObject({kind:"invalid"});await expect(initializeOwner({...config,projectUrl:"https://foreign.example"},"sb_secret_test","a-long-synthetic-password",AbortSignal.timeout(5000),f,path)).rejects.toMatchObject({kind:"unavailable"});expect(f).not.toHaveBeenCalled();});
it("sets only the provisioned user, verifies owner sign-in and consumes the armed file",async()=>{const f=vi.fn().mockResolvedValueOnce(Response.json({id})).mockResolvedValueOnce(Response.json({access_token:"synthetic.token",refresh_token:"synthetic-refresh",expires_in:3600})).mockResolvedValueOnce(Response.json({id,is_anonymous:false})).mockResolvedValueOnce(Response.json({owner:true,assured:false}));const result=await initializeOwner(config,"sb_secret_test","a-long-synthetic-password",AbortSignal.timeout(5000),f,path);expect(result.state.assured).toBe(false);expect(f.mock.calls[0][0]).toBe(`${config.projectUrl}/auth/v1/admin/users/${id}`);expect(f.mock.calls[0][1].method).toBe("PUT");expect(await ownerSetup(path)).toBeNull();expect(await readFile(`${path}.${id}.completed`,"utf8")).not.toContain("password");});
it("an uncertain password update cannot silently run again",async()=>{const f=vi.fn().mockRejectedValue(new Error("Connection lost"));await expect(initializeOwner(config,"sb_secret_test","a-long-synthetic-password",AbortSignal.timeout(5000),f,path)).rejects.toThrow();await expect(initializeOwner(config,"sb_secret_test","another-long-synthetic-password",AbortSignal.timeout(5000),f,path)).rejects.toMatchObject({kind:"conflict"});expect(f).toHaveBeenCalledTimes(1);});
it("does not accept an update receipt for a different account",async()=>{const f=vi.fn().mockResolvedValueOnce(Response.json({id:"20000000-0000-4000-8000-000000000001"}));await expect(initializeOwner(config,"sb_secret_test","a-long-synthetic-password",AbortSignal.timeout(5000),f,path)).rejects.toMatchObject({kind:"unavailable"});expect(f).toHaveBeenCalledTimes(1);});
