/** @vitest-environment node */
import {it,expect,vi} from "vitest";
import {ownerOperations,parseDraftSave} from "./owner-operations";
import {ownerAuth} from "./owner-session";
const id="10000000-0000-4000-8000-000000000001";
const draft={id,requestId:id,revision:0,title:"Verified source",body:"Verified fact",provenance:"Owner evidence",status:"draft" as const};
it("rebuilds draft input without accepting author, revision receipts or publish fields",()=>{expect(parseDraftSave({...draft,author_id:"other",published:true})).toEqual(draft);for(const value of [{...draft,revision:-1},{...draft,status:"published"},{...draft,body:"x".repeat(20001)},{...draft,requestId:"bad"}])expect(()=>parseDraftSave(value)).toThrow();});
it("uses the same caller-supplied request ID for save retries and validates the receipt",async()=>{const call=vi.fn().mockResolvedValue({id,revision:1}),ops=ownerOperations(call);expect(await ops.saveDraft("token",draft)).toEqual({id,revision:1});await ops.saveDraft("token",draft);expect(call.mock.calls[0]).toEqual(call.mock.calls[1]);expect(call.mock.calls[0][2]).toEqual({p_id:id,p_request_id:id,p_expected_revision:0,p_title:draft.title,p_body:draft.body,p_provenance:draft.provenance,p_status:"draft"});call.mockResolvedValue({id,revision:9});await expect(ops.saveDraft("token",draft)).rejects.toMatchObject({kind:"unavailable"});});
it("requires current owner MFA before a report or draft mutation reaches PostgREST",async()=>{const f=vi.fn().mockImplementation((url:string)=>Promise.resolve(Response.json(url.endsWith('/user')?{id,is_anonymous:false}:{owner:true,assured:false})));const auth=ownerAuth({projectUrl:"https://example.supabase.co",publishableKey:"sb_publishable_test"},AbortSignal.timeout(5000),f);await expect(auth.report("token",7)).rejects.toMatchObject({kind:"unauthorized"});await expect(auth.saveDraft("token",draft)).rejects.toMatchObject({kind:"unauthorized"});expect(f.mock.calls.some(c=>String(c[0]).includes("ev_save_draft")||String(c[0]).includes("ev_owner_report"))).toBe(false);});
it("bounds report windows and rejects impossible coverage instead of displaying invented metrics",async()=>{const call=vi.fn(),ops=ownerOperations(call);await expect(ops.report("token",365 as 7)).rejects.toMatchObject({kind:"invalid"});expect(call).not.toHaveBeenCalled();call.mockResolvedValue({days:7,asOf:new Date().toISOString(),from:new Date().toISOString(),truncated:false,questions:1,conversations:1,replies:0,events:1,feedback:0,helpful:0,topQuestions:[],sources:[],outcomes:{}});await expect(ops.report("token",7)).rejects.toMatchObject({kind:"unavailable"});});
it("validates draft identifiers before constructing filters and bounds history",async()=>{const call=vi.fn(),ops=ownerOperations(call);await expect(ops.draft("token","x&select=*")).rejects.toMatchObject({kind:"invalid"});expect(call).not.toHaveBeenCalled();call.mockResolvedValue(Array.from({length:21},()=>({})));await expect(ops.history("token",id)).rejects.toMatchObject({kind:"unavailable"});});
