import { Activity, BookOpen, CheckCircle2, Clock3, FileText, ShieldCheck } from "lucide-react";
import type { CorpusSnapshot, WorkspaceState } from "@/lib/management/types";
import type { Report } from "./ManagementWorkspace";
import { Metric, shortSource, Tag } from "./shared";
import styles from "./management.module.css";

export function Sources({ corpus, sources, selectedSource, selectSource, report, days }: {
  corpus: CorpusSnapshot; sources: string[]; selectedSource: string | null; selectSource: (s: string) => void; report: Report; days: number;
}) {
  const activeSource = selectedSource ?? sources[0];
  const sourceChunks = corpus.chunks.filter((c) => c.source === activeSource);
  return <>
    <div className={styles.metrics}><Metric label="Source documents" value={sources.length} note="Canonical portfolio corpus" icon={<BookOpen size={18} />} /><Metric label="Indexed chunks" value={corpus.chunks.length} note={`${corpus.targetWords}-word target · ${corpus.overlapWords}-word overlap`} icon={<FileText size={18} />} /><Metric label="Largest chunk" value={Math.max(...corpus.chunks.map((c) => c.tokens))} note="Tokens including heading and special tokens" icon={<Activity size={18} />} /><Metric label="Over the token limit" value={corpus.chunks.filter((c) => c.tokens > corpus.tokenLimit).length} note={`${corpus.tokenLimit}-token model window`} icon={<ShieldCheck size={18} />} /></div>
    <div className={styles.knowledgeGrid}><section className={styles.card}><div className={styles.cardHeading}><div><h2>Source library</h2><p>Actual corpus · read-only snapshot</p></div></div>{sources.map((s) => <button className={`${styles.draftRow} ${activeSource === s ? styles.selected : ""}`} key={s} onClick={() => selectSource(s)}><BookOpen size={17} aria-hidden="true" /><span><strong>{shortSource(s)}</strong><small>{corpus.chunks.filter((c) => c.source === s).length} chunks</small></span></button>)}</section><section className={styles.card}><div className={styles.cardHeading}><div><h2>{shortSource(activeSource)}</h2><p>{activeSource}</p></div><Tag tone="green">{sourceChunks.length} chunks</Tag></div><div className={styles.chunkList}>{sourceChunks.map((c) => <details key={c.index} className={styles.chunk} open={sourceChunks.length < 3 || undefined}><summary><span><span className={styles.chunkIndex}>#{String(c.index).padStart(2, "0")}</span>{c.section ?? (c.page ? `Page ${c.page}` : c.source)}</span><Tag>{c.tokens} tokens</Tag></summary><p>{c.text}</p><small>Indexed text SHA-256: {c.indexedSha256}</small></details>)}</div></section></div>
    <section className={`${styles.card} ${styles.snapshot}`}><h2>Retrieval snapshot</h2><dl><div><dt>Embedding model</dt><dd>{corpus.model} · 384 dimensions</dd></div><div><dt>Corpus SHA-256</dt><dd>{corpus.corpusSha256}</dd></div><div><dt>Tokenizer SHA-256</dt><dd>{corpus.tokenizerSha256}</dd></div></dl><p>Exact counts use untruncated indexed text. This snapshot confirms chunk fit, not that this model is the best. Comparative retrieval evaluation remains a release task.</p></section>
    <section className={styles.card}><div className={styles.cardHeading}><div><h2>Source exposure in sample conversations</h2><p>Last {days} days · retrieved, cited and explicitly rated counts</p></div></div><div className={styles.tableScroll} tabIndex={0} role="region" aria-label="Source exposure table"><table className={styles.table}><thead><tr><th>Source</th><th>Retrieved</th><th>Cited</th><th>Helpful / rated citations</th></tr></thead><tbody>{report.sourceSignals.map((s) => <tr key={s.source}><th scope="row">{shortSource(s.source)}</th><td>{s.retrieved}</td><td>{s.cited}</td><td>{s.helpful} / {s.rated}</td></tr>)}</tbody></table></div><p className={styles.cardNote}>Zero citations means no exposure in this sample window. It is not a measure of disinterest. Click events are not collected.</p></section>
  </>;
}

export function Quality({ corpus, store, report }: { corpus: CorpusSnapshot; store: WorkspaceState | null; report: Report }) {
  return <>
    <div className={styles.qualityLead}><span className={styles.sectionIcon}><ShieldCheck size={26} aria-hidden="true" /></span><div><p className={styles.eyebrow}>RELEASE READINESS</p><h2>Ready to explore. Still being qualified.</h2><p>This preview lets you evaluate the management experience. Live user storage and public release have their own gates.</p></div><Tag tone="amber">Local preview</Tag></div>
    <div className={styles.twoColumns}><section className={styles.card}><div className={styles.cardHeading}><div><h2>Evidence & boundaries</h2><p>What the current workspace can establish</p></div></div><ul className={styles.checklist}><li><CheckCircle2 aria-hidden="true" /><span><strong>Actual chunk inspection</strong><small>{corpus.chunks.length} chunks; {Math.max(...corpus.chunks.map((c) => c.tokens))} maximum tokens; no truncation.</small></span></li><li><CheckCircle2 aria-hidden="true" /><span><strong>Local draft workflow</strong><small>Drafts and review notes persist in the local workspace.</small></span></li><li><Clock3 aria-hidden="true" /><span><strong>Live conversation storage</strong><small>Supabase authentication, row access and retention must be qualified.</small></span></li><li><Clock3 aria-hidden="true" /><span><strong>Embedding and answer quality</strong><small>Run the candidate comparison and complete human answer review.</small></span></li><li><Clock3 aria-hidden="true" /><span><strong>Single application host</strong><small>Qualify both Python workloads and shared budget admission on Vercel.</small></span></li></ul></section>
    <section className={styles.card}><div className={styles.cardHeading}><div><h2>Operations snapshot</h2><p>Local workspace and synthetic events only</p></div></div><dl className={styles.operations}><div><dt>Model requests from this preview</dt><dd>None</dd></div><div><dt>Raw visitor transcripts collected</dt><dd>None</dd></div><div><dt>Saved local drafts</dt><dd>{store?.drafts.length ?? "Unavailable"}</dd></div><div><dt>Workspace revision</dt><dd>{store?.revision ?? "Unavailable"}</dd></div><div><dt>Backup-route sample turns</dt><dd>{report.fallback}</dd></div><div><dt>Provider-failure sample turns</dt><dd>{report.turns.filter((t) => t.outcome === "provider_failure").length}</dd></div><div><dt>Live retention job</dt><dd>Not configured</dd></div><div><dt>Live storage notice</dt><dd>Required before collection</dd></div></dl></section></div>
    <section className={`${styles.card} ${styles.publishFlow}`}><h2>From a question to a better answer</h2><ol>{["Review the gap", "Verify the source", "Save a draft", "Validate chunks", "Run evaluations", "Approve & release"].map((step, i) => <li key={step}><span>{String(i + 1).padStart(2, "0")}</span>{step}</li>)}</ol><p>Draft status is an editorial signal. Only a verified, owner-approved release changes the published corpus.</p></section>
  </>;
}
